### ISSUE TITLE
Push k8s-prow infra code

### ISSUE THREAD

**Issue by mkumatag** [ppc64le-cloud/test-infra#1]
This task is to push the infra code for creating the k8s-prow cluster in the IBM Cloud

**Comment by ltccci** [comment]
@mkumatag: [![dog image](https://random.dog/12891d66-40e5-4c95-a7d3-87e28425894a.jpg)](https://random.dog/12891d66-40e5-4c95-a7d3-87e28425894a.jpg)

<details>

In response to [this](https://github.com/ppc64le-cloud/test-infra/issues/1#issuecomment-665564696):

>/woof


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by ltccci** [comment]
@mkumatag: ![cat image](https://cdn2.thecatapi.com/images/3o8.jpg)

<details>

In response to [this](https://github.com/ppc64le-cloud/test-infra/issues/1#issuecomment-672952182):

>/meow


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by mkumatag** [comment]
Not needed anymore, hence closing it.
