### ISSUE TITLE
post-submit job for all-in-one

### ISSUE THREAD

**Issue by mkumatag** [ppc64le-cloud/test-infra#116]

**Comment by RagniGarg97** [comment]
https://github.com/ppc64le-cloud/test-infra/pull/141

**Comment by ltccci** [comment]
@RagniGarg97: Closing this issue.

<details>

In response to [this](https://github.com/ppc64le-cloud/test-infra/issues/116#issuecomment-791155013):

>/close


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>
