### ISSUE TITLE
Write postsubmit image build job for test-infra/images

### ISSUE THREAD

**Issue by mkumatag** [ppc64le-cloud/test-infra#120]
Write postsubmit image build job for https://github.com/ppc64le-cloud/test-infra/tree/master/images

**Comment by RagniGarg97** [comment]
All the issues under this epic are fixed.
Hence closing the epic.

/close

**Comment by ltccci** [comment]
@RagniGarg97: Closing this issue.

<details>

In response to [this](https://github.com/ppc64le-cloud/test-infra/issues/120#issuecomment-791155747):

>All the issues under this epic are fixed.
>Hence closing the epic.
>
>/close


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>
