### ISSUE TITLE
Bump the terraform version in the all-in-one image

### ISSUE THREAD

**Issue by mkumatag** [ppc64le-cloud/test-infra#142]
Please bump the TF version to https://github.com/ppc64le-cloud/test-infra/blob/master/images/all-in-one/Dockerfile#L7

TF version can be bumped to the latest release

**Comment by RagniGarg97** [comment]
fix: https://github.com/ppc64le-cloud/test-infra/pull/172

**Comment by mkumatag** [comment]
This is already fixed.
