### ISSUE TITLE
Allow cherry-pick on ocp-power-automation

### ISSUE THREAD

**Issue by yussufsh** [ppc64le-cloud/test-infra#143]
As we have multiple release branch in ocp4-upi-power{vm|vs} repos, we need the cherry-pick bot to created PRs on required release branch once master PR is merged.

We need to add external plugin called cherrypick.

We need the following things to make it work:

- [ ] Cherrypicker endpoint(EP) deployment which handles these events from the PR
- [ ] Plugin modification for prow to route the traffic to the external EP - https://github.com/ppc64le-cloud/test-infra/pull/144

**Comment by mkumatag** [comment]
Here is the sample deployment file https://github.com/openshift/release/blob/aca5147594181af5d0fa8298957f87640934c6c7/clusters/app.ci/prow/03_deployment/cherrypick.yaml, similar deployment file can be created for our prow cluster.

**Comment by yussufsh** [comment]
Any update on the endpoint?
We have many PRs and getting added everyday waiting for this feature. :-)

**Comment by mkumatag** [comment]
> Any update on the endpoint?
> We have many PRs and getting added everyday waiting for this feature. :-)

We are working on this, soon will deliver this.

**Comment by Rajalakshmi-Girish** [comment]
https://github.com/ppc64le-cloud/test-infra/pull/156

**Comment by yussufsh** [comment]
I have a candidate PR for cherry-picking which is not initiating the process. https://github.com/ocp-power-automation/ocp4-upi-powervm/pull/188.
Please have a look.

**Comment by Rajalakshmi-Girish** [comment]
I believe we need endpoint details to be mentioned in plugins.yaml as in
https://github.com/openshift/release/blob/master/core-services/prow/02_config/_plugins.yaml#L2321

**Comment by yussufsh** [comment]
It is by default `http://<name>` if I am not wrong.

**Comment by Rajalakshmi-Girish** [comment]
> 
> 
> It is by default `http://<name>` if I am not wrong.

Yes, it is. I got to know after looking at https://github.com/kubernetes/test-infra/tree/master/prow/plugins#external-plugins

@mkumatag Am I allowed to create a pod in prow ns in IKS Cluster and confirm below things:
1. Does the Service work by DNS name?
2. If the pod is actually serving.
I also came across https://github.com/kubernetes/test-infra/blob/master/prow/build_test_update.md#how-to-test-a-plugin
https://github.com/kubernetes/test-infra/tree/master/prow/cmd/phony#phony
Please let me know if these would be of any help to confirm **if the added cherrypick endpoint is really working.**

**Comment by Rajalakshmi-Girish** [comment]
https://github.com/ppc64le-cloud/test-infra/pull/159

**Comment by mkumatag** [comment]
we can close this task now, thanks @Rajalakshmi-Girish @yussufsh 
/close

**Comment by ltccci** [comment]
@mkumatag: Closing this issue.

<details>

In response to [this](https://github.com/ppc64le-cloud/test-infra/issues/143#issuecomment-805414087):

>we can close this task now, thanks @Rajalakshmi-Girish @yussufsh 
>/close


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by yussufsh** [comment]
Thanks @Rajalakshmi-Girish
