### ISSUE TITLE
Explore using the ExternalSecret for the credential we use in our project.

### ISSUE THREAD

**Issue by mkumatag** [ppc64le-cloud/test-infra#241]
Ref: https://github.com/external-secrets/kubernetes-external-secrets

**Comment by Rajalakshmi-Girish** [comment]
Have gone through the above reference link and gained an understanding of how `kubernetes-external-secrets` work and on how to use `IBM Cloud Secrets Manager` with `kubernetes-external-secrets`.

But this Secrets Manager was ruled out as currently, ibmcloud is a shared account in our project and many people got access to, and there is always a chance that anyone can get access to the resources accidentally.

**Comment by Rajalakshmi-Girish** [comment]
Started exploring https://github.com/1Password/onepassword-operator.

**Comment by Rajalakshmi-Girish** [comment]
Closing this task as the External Secrets were explored and we started using ESO (https://github.com/external-secrets/external-secrets) in our prow infra.
