### ISSUE TITLE
Explore using search and Sippy tools

### ISSUE THREAD

**Issue by mkumatag** [ppc64le-cloud/test-infra#247]
Lets deploy the following tools for analyzing the results:

https://search.ci.openshift.org - https://github.com/openshift/ci-search
https://github.com/openshift/sippy

/assign @Rajalakshmi-Girish

**Comment by Rajalakshmi-Girish** [comment]
After the below changes to the https://github.com/openshift/ci-search repo and build of `serach.exe` binary, I am able to load and search the jobs from our GCS `ppc64le-kubernetes` on my windows desktop:
```
grep -rl origin-ci-test . | xargs sed -i 's/origin-ci-test/ppc64le-kubernetes/g'
grep -rl "OpenShift" . | xargs sed -i 's/OpenShift/Kubernetes-ppc64le/g'
grep -rl "prow\.ci\.openshift" . | xargs sed -i 's/prow\.ci\.openshift/prow\.ppc64le-cloud/g'
```
![image](https://user-images.githubusercontent.com/63038004/141291702-64cb847b-a275-487a-bed6-05ca55685f71.png)
![image](https://user-images.githubusercontent.com/63038004/141291757-6ae6a950-e9ef-46a1-8e66-a6e38702dd7c.png)

**Comment by Rajalakshmi-Girish** [comment]
@mkumatag I pushed a Docker image with the above changes to the repo. And I see the pod being able to pull the logs from our GCS bucket.
I think once we run it as a service and expose it on IKS, we should be able to view the UI.

**Comment by mkumatag** [comment]
> @mkumatag I pushed a Docker image with the above changes to the repo. And I see the pod being able to pull the logs from our GCS bucket.
> I think once we run it as a service and expose it on IKS, we should be able to view the UI.

wonderful, lemme know once you have the yaml spec.

**Comment by Rajalakshmi-Girish** [comment]
The search tool has been deployed and exposed at https://search.ppc64le-cloud.org/
https://github.com/ppc64le-cloud/test-infra/pull/276
@mkumatag please confirm if this issue can be closed.
