### ISSUE TITLE
load-jenkins-infra-job is failing

### ISSUE THREAD

**Issue by mkumatag** [ppc64le-cloud/test-infra#258]
https://prow.ppc64le-cloud.org/job-history/s3/prow-logs/logs/load-jenkins-infra-job

cc @Rajalakshmi-Girish

**Comment by Rajalakshmi-Girish** [comment]
I see below failure since merge of change https://github.com/ppc64le-cloud/jenkins-infra/pull/80:
```
 INFO:jenkins_jobs.builder:Number of jobs generated:  15
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/jenkins/__init__.py", line 575, in jenkins_request
    return self._response_handler(
  File "/usr/local/lib/python3.8/dist-packages/jenkins/__init__.py", line 536, in _response_handler
    response.raise_for_status()
  File "/usr/local/lib/python3.8/dist-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://jenkins.ppc64le-cloud.org/crumbIssuer/api/json
```
@Shilpi-Das1 ^^

**Comment by Shilpi-Das1** [comment]
It's because jenkins token is not created. Will create it and update that secret

**Comment by mkumatag** [comment]
> It's because jenkins token is not created. Will create it and update that secret

where do you expect this secret to be created?

**Comment by mkumatag** [comment]
> > It's because jenkins token is not created. Will create it and update that secret
> 
> where do you expect this secret to be created?

if it is in the IKS cluster then please sync up with @Rajalakshmi-Girish and ensure that we push that secret to or private repo we maintain for all the secrets cc @sudeeshjohn

**Comment by Shilpi-Das1** [comment]
@mkumatag The job is passing now. The secret is present in IKS cluster @sudeeshjohn  is pushing changes in secret repo
https://prow.ppc64le-cloud.org/job-history/s3/prow-logs/logs/load-jenkins-infra-job

**Comment by mkumatag** [comment]
> @mkumatag The job is passing now. The secret is present in IKS cluster @sudeeshjohn is pushing changes in secret repo
> https://prow.ppc64le-cloud.org/job-history/s3/prow-logs/logs/load-jenkins-infra-job

thanks @Shilpi-Das1, @Rajalakshmi-Girish please ensure this, will close the issue post that

**Comment by mkumatag** [comment]
This is already taken care,

/close
