### ISSUE TITLE
Currency update for the all-in-one image

### ISSUE THREAD

**Issue by mkumatag** [ppc64le-cloud/test-infra#264]
Lets update the all-in-one image with the latest available packages

code: https://github.com/ppc64le-cloud/test-infra/tree/master/images/all-in-one

**Comment by Rajalakshmi-Girish** [comment]
Does this issue mean updating versions of
GOLANG
BAZEL
IBM_CLOUD
TF
TERRAFORM_PROVIDER_IBM
TERRAFORM_PROVIDER_NULL to the latest available versions?

Will this also include verification of all the jobs that use `all-in-one` image. (After the package version updates)

**Comment by mkumatag** [comment]
> Does this issue mean updating versions of
> GOLANG
> BAZEL
> IBM_CLOUD
> TF
> TERRAFORM_PROVIDER_IBM
> TERRAFORM_PROVIDER_NULL to the latest available versions?
> 
> Will this also include verification of all the jobs that use `all-in-one` image. (After the package version updates)

Yes, let's updat it eveything but no need to t et all jobs, may be one quick run of any job should give us the confidence..

**Comment by Rajalakshmi-Girish** [comment]
Done via https://github.com/ppc64le-cloud/test-infra/pull/336 Hence closing.
@mkumatag
