### ISSUE TITLE
merge-method-squash is not working

### ISSUE THREAD

**Issue by mkumatag** [ppc64le-cloud/test-infra#266]
A reviewer can add `/label tide/merge-method-squash` to squash the commits while merging the code but in our prow its not really working, lets debug this and fix it. e.g: https://github.com/ppc64le-cloud/powervs-csi-driver/pull/43

More information: https://github.com/kubernetes/community/blob/692571a6a97f6bbc4bbe478e5ad46fc083570056/contributors/guide/contributor-cheatsheet/README.md#squashing-commits

**Comment by Rajalakshmi-Girish** [comment]
Based on https://github.com/ppc64le-cloud/powervs-csi-driver/pull/43, I verified the logs of hook, prow-controller, tide to see if there is any hint of failure to act upon this label.
But I found no event mentioning the addition of this label to the above PR.
Maybe because it label was added from UI and not through a comment.

**Comment by Rajalakshmi-Girish** [comment]
As per https://github.com/kubernetes/test-infra/blob/master/prow/cmd/tide/config.md#general-configuration, I think adding `squash_label` under the tide section of config.yaml shall enable this feature.

Like in upstream https://github.com/kubernetes/test-infra/blob/master/config/prow/config.yaml#L658

Kindly let me know if verification of this on test prow cluster is needed?
Else, can we give it a try by submitting change directly on our IKS production prow :)

**Comment by mkumatag** [comment]
> As per https://github.com/kubernetes/test-infra/blob/master/prow/cmd/tide/config.md#general-configuration, I think adding `squash_label` under the tide section of config.yaml shall enable this feature.
> 
> Like in upstream https://github.com/kubernetes/test-infra/blob/master/config/prow/config.yaml#L658
> 
> @mkumatag Kindly let me know if verification of this on test prow cluster is needed?
> Else, can we give it a try by submitting change directly on our IKS production prow :)

Let's push the change directly..
