### ISSUE TITLE
k8s conformance jobs indicate uploading the kubectl binary in ARTIFACTS

### ISSUE THREAD

**Issue by Rajalakshmi-Girish** [ppc64le-cloud/test-infra#268]
**Reference:** https://github.com/kubernetes/kubernetes/issues/106264#issuecomment-965627713

**Also, the k8s conformance job trace/log indicates that kubectl binary exists in ARTIFACTS.**
![image](https://user-images.githubusercontent.com/63038004/145626859-b62095f5-88f0-495b-ab64-c583a7814ec8.png)
**Kubernetes binaries like ginkgo, e2e.test, kubectl are observed in the storage bucket where job ARTIFACTS are pushed to.**
![image](https://user-images.githubusercontent.com/63038004/145626685-fb3c24e3-443f-454d-aa8b-50ab752231b1.png)

**Comment by Rajalakshmi-Girish** [comment]
@mkumatag ^^

**Comment by Rajalakshmi-Girish** [comment]
https://github.com/kubernetes-sigs/kubetest2/pull/183

**Comment by Rajalakshmi-Girish** [comment]
Fixed by https://github.com/ppc64le-cloud/kubetest2-plugins/pull/60

**Comment by mkumatag** [comment]
@Rajalakshmi-Girish can you confirm this is not happening anymore in the latest builds?

**Comment by Rajalakshmi-Girish** [comment]
@mkumatag Yes this is not happening in the latest job that ran after the merge of [PR](https://github.com/ppc64le-cloud/kubetest2-plugins/pull/60) to update `kubetest2` in `kubetest2-plugins` this morning.

https://prow.ppc64le-cloud.org/view/gs/ppc64le-kubernetes/logs/periodic-kubernetes-containerd-conformance-test-ppc64le/1541635201308823552

**There are no binaries in the GCS artifacts.**
