### ISSUE TITLE
Update base image for ci-search image

### ISSUE THREAD

**Issue by mkumatag** [ppc64le-cloud/test-infra#294]
Update the base image to centos stream8

https://github.com/ppc64le-cloud/test-infra/blob/b7b689b4737ecbed088b4561f3e28b093b7014f7/images/ci-search/Dockerfile#L10

**Comment by Rajalakshmi-Girish** [comment]
I don't see stream8 tag available in docker hub.
@mkumatag shall I use `quay.io/centos/centos:stream8`?
