### ISSUE TITLE
Handle +2 properly in the prow flow

### ISSUE THREAD

**Issue by mkumatag** [ppc64le-cloud/test-infra#313]
This is to fix the discussion in the thread here: https://github.com/ocp-power-automation/ocp4-upi-powervs/pull/419#issuecomment-1144473846

**Comment by mkumatag** [comment]
Have written a mergeable prow external plugin code which will add the `do-not-merge/non-mergeable` label to all the PRs which is not really ready for the merge, there are number of reason for not being merged. The new written plugin consider following states:

**Mergeable states:**
- CLEAN
- HAS_HOOKS
- UNSTABLE

**Non mergeable states:**
- BEHIND
- BLOCKED
- DIRTY
- DRAFT
- UNKNOWN

Code is hosted here - https://github.com/ppc64le-cloud/prow-plugins/tree/main/mergeable

Ref: https://docs.github.com/en/graphql/reference/enums#mergestatestatus

**Comment by Rajalakshmi-Girish** [comment]
> there are number of reason for not being merged.

Does this mean, the plugin adds `do-not-merge/non-mergeable` label to PRs from repos that need 2 approvals and has only one lgtm/approve label?
and thereby stopping them from going into a batch for merging?

**Comment by mkumatag** [comment]
yes, this external plugin adds this label to block the PR to goto merge pool(2+ is one of the reason but it does block for other reasons like rebase and many other reasons)

**Comment by mkumatag** [comment]
We can already see this in action:

<img width="1053" alt="image" src="https://user-images.githubusercontent.com/12646029/174605321-329a9c20-bd57-4a33-b39e-ba81f602492c.png">
