### ISSUE TITLE
Remove ssh_key_secrets from config.yaml

### ISSUE THREAD

**Issue by Rajalakshmi-Girish** [ppc64le-cloud/test-infra#423]
The metadata `ssh_key_secrets` at https://github.com/ppc64le-cloud/test-infra/blob/master/config/prow/config.yaml#L86 doesn't seem to be required.
As per the description here, https://github.com/kubernetes/test-infra/blob/master/prow/config/prow-config-documented.yaml#L746-L748 it is used only during the cloning process. As we are using only public repos, I suppose this is not needed here.

I also do not see this detail in https://github.com/kubernetes/test-infra/blob/master/config/prow/config.yaml

@mkumatag ^^

**Comment by mkumatag** [comment]
fixed via https://github.com/ppc64le-cloud/test-infra/pull/428
