### ISSUE TITLE
baseurl pacakge is outdated.

### ISSUE THREAD

**Issue by chetjain** [ppc64le-cloud/test-infra#459]
The baseurl seems to be obsolete. Not works anymore. Please update
https://pkgs.k8s.io/core:/stable:/v1.29/rpm/

**Comment by chetjain** [comment]
+ yum -y install git curl wget kubelet kubeadm kubectl '--disableexcludes=Kubernetes'
Kubernetes                                                                                   1.3 kB/s | 481  B     00:00
Kubernetes                                                                                    21 kB/s | 1.7 kB     00:00
Importing GPG key 0x9A296436:
 Userid     : "isv:kubernetes OBS Project <isv:[kubernetes@build.opensuse.org](mailto:kubernetes@build.opensuse.org)>"
 Fingerprint: DE15 B144 86CD 377B 9E87 6E1A 2346 54DA 9A29 6436
 From       : https://pkgs.k8s.io/core:/stable:/v1.28/rpm/repodata/repomd.xml.key
Kubernetes                                                                                    78 kB/s |  20 kB     00:00
Package git-2.43.0-1.el9.ppc64le is already installed.
Package curl-7.76.1-28.el9.ppc64le is already installed.
Package wget-1.21.1-7.el9.ppc64le is already installed.
All matches were filtered out by exclude filtering for argument: kubelet
All matches were filtered out by exclude filtering for argument: kubeadm
All matches were filtered out by exclude filtering for argument: kubectl
Error: Unable to find a match: kubelet kubeadm kubectl

**Comment by Rajalakshmi-Girish** [comment]
@chetjain Can you try `yum -y install git curl wget kubelet kubeadm kubectl '--disableexcludes=kubernetes'` instead?

The k in Kubernetes needs to be in lowercase.

The wiki page https://github.com/ppc64le-cloud/test-infra/wiki/Creating-Kubernetes-cluster-with-kubeadm-on-Power-(RHEL-or-CentOS) has been updated.

**Comment by chetjain** [comment]
> @chetjain Can you try `yum -y install git curl wget kubelet kubeadm kubectl '--disableexcludes=kubernetes'` instead?
> 
> The k in Kubernetes needs to be in lowercase.
> 
> The wiki page https://github.com/ppc64le-cloud/test-infra/wiki/Creating-Kubernetes-cluster-with-kubeadm-on-Power-(RHEL-or-CentOS) has been updated.

Yes, that works.
